### ISSUE TITLE
Depuis la mise à jour du core en 3.3.xx le plugin ne fonctionne plus à cause des logs

### ISSUE THREAD

**Issue by superbricolo** [abarrau/jeedom-plugin-ttsWebServer-doc#17]
Bonjour Abarrau, J'ai identifié les anomalies et effectué les modifs pour que cela fonctionne à nouveau. Peut-être que tu pourrais mettre à jour les sources dans le plugin pour que cela profite à tous. Je te joins les sources modifiés. J'ai changé l'extension des .php en .txt pour que cela passe comme fichier joint.
Tu peux aussi regarder le topic https://www.jeedom.com/forum/viewtopic.php?f=142&t=26184&start=420#p713168

[ttsWebServer.class.txt](https://github.com/abarrau/jeedom-plugin-ttsWebServer-doc/files/3095507/ttsWebServer.class.txt)

[olindoteTools.txt](https://github.com/abarrau/jeedom-plugin-ttsWebServer-doc/files/3095500/olindoteTools.txt)

**Comment by abarrau** [comment]
Bonjour, 
Oui ce correctif est bien en visibilité, mais j'ai entamé d'autres devs sur cette version (et je suis un peu bloqué personnellement actuellement, manque de temps). 
Je vais voir si je peux sortir au moins une intermédiaire.

**Comment by abarrau** [comment]
Bjr,
passage en bêta le 24/06, avant passage en stable début juillet.

**Comment by abarrau** [comment]
Anomalie corrigée et validée. Je propose la fermeture.
