### ISSUE TITLE
Petit bug sans importance, si le plugin est vierge de tout ...

### ISSUE THREAD

**Issue by ZitouneOlivier** [abarrau/jeedom-plugin-ttsWebServer-doc#2]
- Petit log "faux", sans webserveur, si tu clic dans la zone "ttswebserver" sur  "Découverte", tu obtiens ce message : "L'objet ttswebserver a etait supprimé..."
- Si tu clic sur ajouter, tu obtiens "[Test]L'adresse ip de l'equipement est vide ou mal formatée" et après c'est mortttttttttttttttt. tu ne peux plus accèder a ton plugin !! Tu es obligé de supprimer le plugin et de le reinstaller.
- Si tu installes ton plugin et tu détectes tes sonos, ils remontent bien. Si tu supprimes ton plugin et que tu le réinstalle, tu tentes alors de synchroniser tes sonos, ils ne remontent plus. A priori, il te faudra ajouter un webserver pour que les Sonos Remontent.

**Comment by abarrau** [comment]
Olivier, 
1/ des vérifications complémentaires ont été ajoutées pour éviter d'avoir le bouton "découverte" si l'objet "TTS Web Service" n'existe pas. 
2/ ce cas n'a pas été reproduit ; peux-je avoir un descriptif des étapes ?
3/ à la réinstallation du plugin, il faut repasser par la page de config pour indiquer les familles de "player" utilisables. 
Par défaut, maintenant tout est sélectionné ; c'est à l'utilisateur de décocher s'il y en a qu'il ne souhaite pas utiliser.

**Comment by abarrau** [comment]
Olivier, si ok pour toi, je clos l'issue, merci

**Comment by ZitouneOlivier** [comment]
Oui, oui aucun problème... J'ai pas eu le temps de rejouer avec, pour être plus précis. Dsl
