### ISSUE TITLE
Pas de commande disponible

### ISSUE THREAD

**Issue by bandit33000** [abarrau/jeedom-plugin-ttsWebServer-doc#5]
Bonjour,

Il semble ne pas y avoir de commandes. Les serveurs sont reconnus et synchronisés.

![2017-05-20 10_52_47-alarme - jeedom](https://cloud.githubusercontent.com/assets/5315032/26274448/9fb215d2-3d4a-11e7-8ce6-73f5d2a0a199.png)

**Comment by abarrau** [comment]
les équipements hébergeant l'application android "TTS WS"  (ce que je suppose vu le nom "TTS-Tablette") n'ont pas de commande actuellement. 
Les commandes diffusions sont toutes centralisés au niveau de l'équipement "server" (celui qui correspond à l'icone d'un globe (en haut de la page) sur la page des équipements)

Ce comportement est donc normal, ce n'est pas un dysfonctionnement.

**Comment by bandit33000** [comment]
D'accord !

Merci pour l'info, effectivement c'est bon.
