### ISSUE TITLE
Problème d'install sur Android 4.1.2

### ISSUE THREAD

**Issue by georgein** [abarrau/jeedom-plugin-ttsWebServer-doc#9]
Bonsoir,
Impossible d'installer l'APK sur un Galaxy S5 GT-N7000 sous la Android 4.1.2 qui ne sert QUE de passerelle SMS, donc propre
L'APK descend bien mais android le refuse avec le message "Problème lors de l'analyse de l'ensemble". Bien sur les autorisation sont OK. J'ai aussi tenté de downloader à la main l'APK mais j'ai le même message d'erreur lorsque je le lance.
Plus curieux, j'ai tenté l'installation sur un Galaxy S7  sous Android 6.0.1 et là tous se passe sans problème ...
Cordialement

**Comment by abarrau** [comment]
Bonjour, 
Comme précisé que le forum, l'application est disponible pour une version minimum 4.4 (build 19). 
Une note a été ajoutée dans la doc. 
Merci pour ce retour. 
Cdt,
